name: Healthcheck

on:
  schedule:    
    - cron: '5/5* * * *'
jobs:
  timed_health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check app in prod
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: https://blogsmono.herokuapp.com/health
          max-attempts: 3
          retry-delay: 5s

