name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]  

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      SECRET: ${{ secrets.SECRET }}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
    steps:
        - name: git checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: '0'
        - name: set node version       
          uses: actions/setup-node@v1
          with:
            node-version: '12.x'            
        - name: npm install
          run: npm install
        - name: lint
          run: npm run lint        
        - name: test backend
          run: npm run test
        - name: build
          run: npm run build
        - name: e2e tests
          uses: cypress-io/github-action@v2
          with:
            command: npm run test:e2e
            start: npm run start:test
            wait-on: http://localhost:3000       
        - name: deploy to heroku
          if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}         
          uses: akhileshns/heroku-deploy@v3.12.12 
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "blogsmono" 
            heroku_email: "petrimus76@gmail.com"
            healthcheck: "https://blogsmono.herokuapp.com/health"
            checkstring: "ok"
            rollbackonhealthcheckfailed: true       
        - name: Bump version and push tag
          if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}          
          uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INITIAL_VERSION: "1.0.0"            
            DEFAULT_BUMP: patch
        - name: Notification success
          if: ${{ success() && github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
          uses: 8398a7/action-slack@v3
          with:
            status: custom
            fields: commit,repo,author
            custom_payload: |
              {
                attachments: [{
                  color: 'good', 
                  text: `A new version of ${process.env.AS_REPO} deployd, commit: (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR}`
                }]
              }         
        - name: Notification failure
          if: ${{ failure() }}
          uses: 8398a7/action-slack@v3
          with:
            status: ${{ job.status }}
            author_name: 'Workflow failed to complete'
            fields: repo,message,commit,author,took